In [77]:
from Discrete import *
from aux import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Questão 1

In [54]:
A = np.array([[1, 0.1], [0.5, 0.1]])
B = np.array([[1],[0.1]])
C = np.array([[1,1]])
D = np.array([[0]])
Ts = None

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [55]:
system.check_stability()

Eigenvalues of the system matrix A:
⎡ 1.05249378105604 ⎤
⎢                  ⎥
⎣0.0475062189439555⎦


False

In [56]:
system.check_controllability()

Controllability Matrix:
⎡1.0  1.01⎤
⎢         ⎥
⎣0.1  0.51⎦
Rank of the Controllability Matrix: 2


True

In [57]:
system.check_observability()

Observability Matrix:
⎡1.0  1.0⎤
⎢        ⎥
⎣1.5  0.2⎦
Rank of the Observability Matrix: 2


True

### Questão 2

In [58]:
A = np.array([[0.0877, 0.1786, -0.0691], [-0.0595, 0.0877, -0.1056], [0, 0, 0.3679]])
B = np.array([[-0.0561],[-0.1438], [0.9482]])
C = np.array([[1, 0, 0]])
D = np.array([[0]])
Ts = None

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [59]:
desired_poles = [-0.5 + 0.5j, -0.5 - 0.5j, 0.5]
k = system.ackermann_state_feedback(desired_poles)
print(f"K = {k}")

K = [[ 15.26471565 -22.16650794  -1.35825068]]


In [60]:
desired_poles_l = [0.9 + 0.1j, 0.9 - 0.1j, 0.1]
l = system.compute_observer_gain(desired_poles_l)
print(f"L = {l}")

L = [[-1.3567    ]
 [ 0.87944691]
 [-2.05456747]]


### Questão 3

In [61]:
A = np.array([[0, 1], [0, 0]])
B = np.array([[0],[1]])
C = np.array([[1, 1]])
D = np.array([[0]])
Ts = 1

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [62]:
system.sys_discrete

StateSpace(array([[1., 1.],
       [0., 1.]]), array([[0.5],
       [1. ]]), array([[1., 1.]]), array([[0.]]), 1)

In [63]:
desired_poles = [0.25 + 0.5j, 0.25 - 0.5j]
k = system.ackermann_state_feedback(desired_poles)
print(f"K = {k}")

K = [[0.8125  1.09375]]


In [64]:
desired_poles_l = [-0.5, 0.5]
l = system.compute_observer_gain(desired_poles_l)
print(f"L = {l}")

L = [[1.25]
 [0.75]]


### Questão 4

In [95]:
num = [3,-2]
den = [1, 1, 0]
Ts = 1

A,B,C = tf_ss(num,den, 'controllable')

In [96]:
print(A)
print("------")
print(B)
print("------")
print(C)

[[ 0.  1.]
 [-1. -0.]]
------
[[0.]
 [1.]]
------
[[-2.  3.]]


In [97]:
system = DiscreteSystemAnalysis(A, B, C, D, Ts)
system.sys_discrete

StateSpace(array([[ 0.54030231,  0.84147098],
       [-0.84147098,  0.54030231]]), array([[0.45969769],
       [0.84147098]]), array([[-2.,  3.]]), array([[0.]]), 1)

In [100]:
system.augment_system()
system.sys_aug

StateSpace(array([[ 0.54030231,  0.84147098,  0.        ],
       [-0.84147098,  0.54030231,  0.        ],
       [ 2.        , -3.        ,  0.        ]]), array([[0.45969769],
       [0.84147098],
       [0.        ]]), array([[-2.,  3.,  1.]]), array([[0.]]))