In [294]:
from Discrete import *
from aux import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Questão 1

In [295]:
A = np.array([[1, 0.1], [0.5, 0.1]])
B = np.array([[1],[0.1]])
C = np.array([[1,1]])
D = np.array([[0]])
Ts = None

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [296]:
system.check_stability()

Eigenvalues of the system matrix A:
⎡ 1.05249378105604 ⎤
⎢                  ⎥
⎣0.0475062189439555⎦


np.False_

In [297]:
system.check_controllability()

Controllability Matrix:
⎡1.0  1.01⎤
⎢         ⎥
⎣0.1  0.51⎦
Rank of the Controllability Matrix: 2


np.True_

In [298]:
system.check_observability()

Observability Matrix:
⎡1.0  1.0⎤
⎢        ⎥
⎣1.5  0.2⎦
Rank of the Observability Matrix: 2


np.True_

### Questão 2

In [299]:
A = np.array([[0.0877, 0.1786, -0.0691], [-0.0595, 0.0877, -0.1056], [0, 0, 0.3679]])
B = np.array([[-0.0561],[-0.1438], [0.9482]])
C = np.array([[1, 0, 0]])
D = np.array([[0]])
Ts = None

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [300]:
desired_poles = [-0.5 + 0.5j, -0.5 - 0.5j, 0.5]
k = system.ackermann_state_feedback(desired_poles)
print(f"K = {k}")

K = [[-15.26471565  22.16650794   1.35825068]]


In [271]:
desired_poles_l = [0.9 + 0.1j, 0.9 - 0.1j, 0.1]
l = system.compute_observer_gain(desired_poles_l)
print(f"L = {l}")

L = [[-1.3567    ]
 [ 0.87944691]
 [-2.05456747]]


### Questão 3

In [301]:
A = np.array([[0, 1], [0, 0]])
B = np.array([[0],[1]])
C = np.array([[1, 1]])
D = np.array([[0]])
Ts = 1

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [307]:
system.sys_discrete

StateSpace(array([[1., 1.],
       [0., 1.]]), array([[0.5],
       [1. ]]), array([[1., 1.]]), array([[0.]]), 1)

In [303]:
desired_poles = [0.25 + 0.5j, 0.25 - 0.5j]
k = system.ackermann_state_feedback(desired_poles)
print(f"K = {k}")

K = [[-0.8125  -1.09375]]


In [281]:
desired_poles_l = [-0.5, 0.5]
l = system.compute_observer_gain(desired_poles_l)
print(f"L = {l}")

L = [[1.25]
 [0.75]]


### Questão 4

In [320]:
num = [3,-2]
den = [1,1,0]
Ts = 1

A,B,C, D = tf_ss(num,den, 'control')


In [309]:
print(A)
print("------")
print(B)
print("------")
print(C)

[[ 0.  1.]
 [ 0. -1.]]
------
[[0.]
 [1.]]
------
[[-2  3]]


In [321]:
system = DiscreteSystemAnalysis(A, B, C, D, Ts)
system.sys_discrete

StateSpace(array([[1.        , 0.63212056],
       [0.        , 0.36787944]]), array([[0.36787944],
       [0.63212056]]), array([[-2.,  3.]]), array([[0.]]), 1)

In [322]:
system.augment_system()

In [328]:
system.A_aug


array([[1.        , 0.63212056, 0.36787944],
       [0.        , 0.36787944, 0.63212056],
       [0.        , 0.        , 0.        ]])

In [333]:
poles = [0.5 + 0.2j, 0.5 - 0.2j, -0.1]
k1,k2 = system.reference_tracker_gain(poles)

[ 1.    -0.9    0.19   0.029]
-------
[[ 0.319       0.29211759  0.29363862] 
 [ 0.          0.02688241 -0.00363862] 
 [ 0.          0.          0.029     ]]
-------
[[ 0.          0.          1.        ] 
 [-0.58197671  1.92067359  0.        ] 
 [ 1.58197671 -0.92067359  0.        ]]
[ 1.    -0.9    0.19   0.029]
-------
[[ 0.319       0.29211759  0.29363862] 
 [ 0.          0.02688241 -0.00363862] 
 [ 0.          0.          0.029     ]]
-------
[[ 0.          0.          1.        ] 
 [-0.58197671  1.92067359  0.        ] 
 [ 1.58197671 -0.92067359  0.        ]]
kkkkkkk
[[-0.50465057 -0.4373733  -0.46787944]]


In [331]:
k1

np.float64(0.25232528474565763)

In [332]:
k2

array([-0.15757803,  0.4702281 ])

### Questão 5

In [315]:
A = np.array([[1, 0, 2], [0, 1, 0], [2, 3, -1]])
B = np.array([[-1],[2], [0]])
C = np.array([[1, 0, 1]])
D = np.array([[0]])
Ts = None

system = DiscreteSystemAnalysis(A, B, C, D, Ts)

In [316]:
system.augment_system()


In [317]:
poles = [0.5 + 0.5j, 0.5 - 0.5j, -0.5 + 0.5j, -0.5 - 0.5j]
k1,k2 = system.reference_tracker_gain(poles)

In [318]:
k1

np.float64(-0.10416666666666696)

In [319]:
k2

array([-1.36979167, -0.73697917, -1.421875  ])