In [163]:
from Continuous import *
from aux import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### Questão 1

#### Sistema A

In [6]:
A = np.array([[-4, 3 , 0], [-1, -4, -1], [0,0,-2]])
B = np.array([[0],[0], [3]])
C = np.array([[1, 0, 0]])
D = np.array([[0]])

system = ContinousSystemAnalysis(A, B, C, D)

In [7]:
system.char_poly()

s**3 + 10*s**2 + 35*s + 38

In [8]:
system.check_stability()

Eigenvalues of the system matrix A:
⎡-4.0 + 1.73205080756888⋅ⅈ⎤
⎢                         ⎥
⎢-4.0 - 1.73205080756888⋅ⅈ⎥
⎢                         ⎥
⎣          -2.0           ⎦


np.True_

In [9]:
system.check_controllability()

Controllability Matrix:
⎡0.0  0.0   -9.0⎤
⎢               ⎥
⎢0.0  -3.0  18.0⎥
⎢               ⎥
⎣3.0  -6.0  12.0⎦
Rank of the Controllability Matrix: 3


np.True_

In [10]:
system.check_observability()

Observability Matrix:
⎡1.0    0.0   0.0 ⎤
⎢                 ⎥
⎢-4.0   3.0   0.0 ⎥
⎢                 ⎥
⎣13.0  -24.0  -3.0⎦
Rank of the Observability Matrix: 3


np.True_

#### Sistema B

In [11]:
A = np.array([[-5, 1 , 0], [2, 7, -1], [0,-3,6]])
B = np.array([[0],[0], [1]])
C = np.array([[1, -2, 3]])
D = np.array([[0]])

system = ContinousSystemAnalysis(A, B, C, D)

In [12]:
system.char_poly()

s**3 - 8*s**2 - 28*s + 207

In [13]:
system.check_stability()

Eigenvalues of the system matrix A:
⎡-5.16807496502934⎤
⎢                 ⎥
⎢8.39951290420461 ⎥
⎢                 ⎥
⎣4.76856206082472 ⎦


np.False_

In [15]:
system.check_controllability()

Controllability Matrix:
⎡0.0  0.0   -1.0 ⎤
⎢                ⎥
⎢0.0  -1.0  -13.0⎥
⎢                ⎥
⎣1.0  6.0   39.0 ⎦
Rank of the Controllability Matrix: 3


np.True_

In [14]:
system.check_observability()

Observability Matrix:
⎡1.0    -2.0    3.0 ⎤
⎢                   ⎥
⎢-9.0  -22.0   20.0 ⎥
⎢                   ⎥
⎣1.0   -223.0  142.0⎦
Rank of the Observability Matrix: 3


np.True_

### Questão 2

In [19]:
A,B,C,D = input_matrices()

Enter the system order:  3


Enter the entries for matrix A (3x3) row by row, separated by commas:


Row 1:  -4, 3, 0
Row 2:  -1, -4, -1
Row 3:  0, 0, -2


Enter the entries for matrix B (3x1), one entry per line:


Entry 1:  0
Entry 2:  0
Entry 3:  3


Enter the entries for matrix C (1x{n}), separated by commas:


Row:  1, 0, 0


Enter the entry for matrix D (1x1):


Entry:  0


In [20]:
system = ContinousSystemAnalysis(A,B,C,D)

In [23]:
desired_poles = [-2 + 1j, -2 - 1j, -10]
k = system.ackermann_state_feedback(desired_poles)
print(f"K = {k}")

K = [[ 2.66666667 -7.33333333 -1.33333333]]


In [24]:
desired_poles_l = [-1 + 1j, -1 - 1j, -10]
l = system.compute_observer_gain(desired_poles_l)
print(f"L = {l}")

L = [[ 2.        ]
 [-8.33333333]
 [-5.33333333]]


### Questão 3

In [46]:
A,B,C,D = input_matrices()

Enter the system order:  3


Enter the entries for matrix A (3x3) row by row, separated by commas:


Row 1:  -5, 1, 0
Row 2:  2, 7, -1
Row 3:  0, -3, 6


Enter the entries for matrix B (3x1), one entry per line:


Entry 1:  0
Entry 2:  0
Entry 3:  1


Enter the entries for matrix C (1x{n}), separated by commas:


Row:  1, -2, 3


Enter the entry for matrix D (1x1):


Entry:  0


In [47]:
system = ContinousSystemAnalysis(A,B,C,D)

In [48]:
desired_poles = [-2 + 1j, -2 - 1j, -10]
k = system.ackermann_state_feedback(desired_poles)
print(f"K = {k}")

K = [[ 72. 117. -22.]]


In [49]:
desired_poles_l = [-1 + 1j, -1 -1j, -10]
l = system.compute_observer_gain(desired_poles_l)
print(f"L = {l}")

L = [[-0.15579035]
 [-8.56453284]
 [ 1.00890822]]


### Questão 4

In [112]:
A,B,C,D = input_matrices()

Enter the system order:  3


Enter the entries for matrix A (3x3) row by row, separated by commas:


Row 1:  -6, 1 ,0
Row 2:  -11, 0, 1
Row 3:  -6, 0, 0


Enter the entries for matrix B (3x1), one entry per line:


Entry 1:  2
Entry 2:  6
Entry 3:  2


Enter the entries for matrix C (1x{n}), separated by commas:


Row:  1, 0 , 0


Enter the entry for matrix D (1x1):


Entry:  0


In [113]:
system = ContinousSystemAnalysis(A,B,C,D)

In [115]:
system.B.shape

(3, 1)

In [36]:
desired_poles = [-1 + 0.1j, -1 - 0.1j, -5, -12]
system.augment_system()

In [43]:
k1, k2 = system.reference_tracker_gain(desired_poles)


In [44]:
k1

np.float64(30.299999999999596)

In [45]:
k2

array([-84.325,  33.085,  -8.43 ])

### Questão 5

In [124]:
num = [3,4,-2]
den = [1,3,7,5]

A,B,C,D = tf_ss(num,den, 'control')

system = ContinousSystemAnalysis(A, B, C, D)

In [128]:
system.sys

Observability Matrix:
⎡-2.0    4.0   3.0 ⎤
⎢                  ⎥
⎢-15.0  -23.0  -5.0⎥
⎢                  ⎥
⎣25.0   20.0   -8.0⎦
Rank of the Observability Matrix: 3


np.True_

In [136]:
poles = [-1, -1, -2]
ackermann_observer_gain(system.A, system.C, poles)

array([[-0.09543568],
       [ 0.31120332],
       [-0.14522822]])

In [137]:
poles = [-4, -4, -5]
system.ackermann_state_feedback(poles)

array([[-75., -49., -10.]])

### Questão 6

In [196]:
num = [2, 1]
den = [1, 3, 0]

A,B,C,D = tf_ss(num,den, 'control')

system = ContinousSystemAnalysis(A, B, C, D)

In [197]:
system.sys

StateSpace(array([[ 0.,  1.],
       [ 0., -3.]]), array([[0.],
       [1.]]), array([[1., 2.]]), array([[0.]]))

In [198]:
system.augment_system()

In [199]:
k1, k2 = system.reference_tracker_gain([-1, -1, -1])

In [200]:
k1

np.float64(-1.0)

In [201]:
k2

array([-1.,  0.])

### Questão 7

In [173]:
num = [0, 3]
den = [1, 2, -4]

A,B,C,D = tf_ss(num,den, 'observe')

system = ContinousSystemAnalysis(A, B, C, D)

(1, 2)


In [174]:
system.sys

StateSpace(array([[ 0.,  4.],
       [ 1., -2.]]), array([[3.],
       [0.]]), array([[0., 1.]]), array([[0.]]))

In [175]:
system.augment_system()

In [176]:
k1, k2 = system.reference_tracker_gain([-2, -2, -3])

In [177]:
k1

np.float64(4.0)

In [178]:
k2

array([1.66666667, 3.33333333])

In [181]:
ackermann_control_gain(system.A_aug, system.B_aug, [-2,-2,-3])

array([[-4.        , -1.66666667, -3.33333333]])

### Exemplo Livro

In [182]:
A = np.array([[0, 1], [-2, -2]])
B = np.array([[0], [1]])
C = np.array([[1,0]])
D = np.array([[0]])

In [183]:
system = ContinousSystemAnalysis(A,B,C,D)

In [188]:
system.augment_system()
system.A_aug
system.B_aug

array([[0.],
       [0.],
       [1.]])

In [193]:
k1, k2 = system.reference_tracker_gain([-10, -1 + 1j, -1 - 1j])

In [194]:
k1

np.float64(-20.0)

In [195]:
k2

array([-20., -10.])

In [192]:
ackermann_control_gain(system.A_aug, system.B_aug, [-10, -1 + 1j, -1 - 1j])

array([[-20., -20., -10.]])